### ISSUE TITLE
Interface for gridData

### ISSUE THREAD

**Issue by adityam** [sisl/GridInterpolations.jl#1]
Wouldn't it be better if the `gridData` is provided as a mufti-dimensional array rather than a vector? Consider the example given in the README: 

```
gridData = [8. 1. 6. 3. 5. 7. 4. 9. 2.]             # value data at each cut
```

It is not clear whether the data is provided in row-major or col-major form (and this gets more complicated for higher dimensions). An alternative is to have an interface where

```
gridData = [8. 1. 6.; 3. 5. 7.; 4. 9. 2.]
```
so that it is clear that `gridData[0, 0.5] = 3.` etc. Internally, this could be as simple vectorizing the array and then proceedings as one is doing now.

**Comment by mykelk** [comment]
I added support for this just now. Thanks!

**Comment by adityam** [comment]
Thanks
