### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by zsunberg** [sisl/GridInterpolations.jl#22]
I think this package has enough changes (especially those from March 18 and 19) to warrant tagging a new version, especially since the types are parameterized by the dimension now.

@Shushman , you probably have been using this the most. What do you think? are there any changes coming up?

**Comment by Shushman** [comment]
Hmm well we do have the new type parameterization as well as the `vertices` method which the other packages that I'm trying to get registered soon (`LocalFunctionApproximation` and `LocalApproximationValueIteration`) do depend on, so I'm in favour of tagging a new version.

**Comment by Shushman** [comment]
This is done!
