### ISSUE TITLE
Compat with StaticArrays

### ISSUE THREAD

**Issue by johannes-fischer** [sisl/GridInterpolations.jl#35]
For some reason the [general registry](https://github.com/JuliaRegistries/General/blob/master/G/GridInterpolations/Compat.toml) requires StaticArrays = "0.0.0 - 0.12" for this package, hence it cannot be used together with packages requiring StaticArrays >1.0

**Comment by mykelk** [comment]
Ah, interesting. Would you mind submitting a PR?
