### ISSUE TITLE
Unnecessary heap allocation?

### ISSUE THREAD

**Issue by himanshugupta1009** [sisl/GridInterpolations.jl#41]
This line https://github.com/sisl/GridInterpolations.jl/blob/fa8cd12253713b3a236d04128c69936533d5c0c9/src/GridInterpolations.jl#L231 allocates new vectors. 

It seems like over-optimization to save a few Float computations at the expense of allocations which stresses the garbage collector. Is there a way to get around it? If not, is it possible to just avoid the extra check performed at line 229?

Thanks!

**Comment by mykelk** [comment]
Thanks for the idea! Feel free to contribute a PR with some empirical results on timing.

**Comment by himanshugupta1009** [comment]
I have created a PR for this issue with some empirical results. If there are any issues with it, let me know. Thanks!
